language: node_js
node_js:
- '8'

cache: yarn

notifications:
  email: false
  pushover:
    api_key:
      secure: YEE/fEa2Et5N1G6462QEFU+J12JEqlKrRhMeafuLheIsT/W/mUpkY6a5ui0ZjuC2lvGtVf4Ck8sXAyxUBFQ+YHMYDgAvrPQXIcaeqW0/f6W3N7lldotM3qIYFU0q+bYRFSkJvZftC33QQ2wUyX5d9qfDNMK72QoXDAUxQBs8Uz+tqubFt/XHHzSCzH2pjckDCHbbY2sOg7+MEjQhZK/YKRfe9CBhbf7QWdstJB5YH2rUhqj8CVT85h9VN17N/i3eljS65T8JkKA7NBVUjj/qBYvz+CBx4HwjukJVH+eRahlhH6Ae1iT/3a4sRTwPbl/qOcabs5k92JLf94v/iY2+1pl+S4OIp8llp29WjIiKfvKkKj6uE678w90sdVhcbewt+QSaZMrRmu9DkPglSsdRhY8fy+jqpoX6Jm21Wqx6M4Yqpr3JDoz9FkRgBIwVN5NEKt6rmqDfybJz60/ZvIX6Npc1DLWEWWgHcAhfw2ZCTU7skSLpjB8GnNGd5NYYOCBll7bA0fWYriGGsj6MrH9x6xi2yvodX/CiDzIdRbJI3Ptt9WAjZ24JWWj+NS6en15nEx1lamTcwXXboX/5cic+sbwLNiegv//YaMIvhGHAZXLWvKZuNx6hmShbBWt5/J0VuVZs+lpZa6SNdxMFRlJKCaUB8frtuFvSYNnMdDy4tws=
    users:
      secure: b+5tffTlgvhS0uXW/MgH/QIRJGMtYsQ6ctbyFBHB1Mt7oOrsDiy667r4UHFSuOAzDD9BOpFpucrjwhwISIGuuGH14PvMqbQuaK0vNBcFuHe1qnf/uF0uCxRbK0TuhlAqJi/tF8oz4dnRASDY4Oihcx+hPdeoL7KZe9ls5telTH8M1DzHHkiMB4p2fO/WyOFn4IaO420RPOPJIZEdyZl3YQSZrGnWg+3QxOuGJFRqaVMgzyh0XjNcD55w/OpUZVzV/nP0dSv2KbHMG20KVsOnQUWkdJY/uRik78vC6DNlrslPUoGuBBPo+lrsHMm3BUSdTApJB6dLMVYU33oe4KaZ/1Z5VJFNqDbzv/Bw8TfSitu4Vjw3r9jom1ioAG0kPV8/jXPtttvVKZofRN9maCDBbTlIqZ342BnNwO8agnGYfpQkHQHMcw+Fx+/ezu1Aw/tSn2151IBwbV3au9e6WaGGZnxojEae6pqZYLVFwKj8J+214u5rbGCYlkrRn0lNxsPjvpQXnsem82NuaMY42sNusm1rdi3DdlnljrrVEPZcYTEEfcQbcv6UqogcQUDcdgcS9Dq7cAxufeHJyRz1psyI8/iGBxCCxNRV4kYSuHbp9GXZryHJsIBkff7AF4XbDwOU3m3+bd6TdYmMemWXY+OaeO8sPpRRwz9Nu0EufgAxRNA=
